name: no_tomorrow
description: A simple todo app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/light_splash_logo.png"
  color_dark: "#000000"
  image_dark: "assets/images/dark_splash_logo.png"
  assets:
    - assets/images/app_icon.png
    - assets/images/dark_splash_logo.png
    - assets/images/light_splash_logo.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800